# Generated by Django 5.1.6 on 2025-08-14 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('code', models.IntegerField()),
                ('credits', models.IntegerField()),
                ('hours_needed', models.IntegerField()),
            ],
        ),
    ]
