# Generated by Django 5.1.6 on 2025-08-14 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0003_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='professor',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='college.professor'),
        ),
    ]
