# Generated by Django 5.1.6 on 2025-08-17 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0005_student_course_student_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='professor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='college.professor'),
        ),
    ]
