# Generated by Django 5.1.6 on 2025-08-17 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0006_alter_course_professor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_course',
            name='semester_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student_course',
            name='semester_year',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='student_course',
            unique_together={('student', 'course', 'semester_year', 'semester_number')},
        ),
    ]
